# Generated by Django 4.0.2 on 2022-02-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(max_length=255)),
                ('about', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=127, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('forks', models.IntegerField(blank=True, null=True)),
                ('watchers', models.IntegerField(blank=True, null=True)),
                ('commits_number', models.IntegerField(blank=True, null=True)),
                ('release_version', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('release_changelog', models.TextField(blank=True, null=True)),
                ('commit_author', models.CharField(blank=True, max_length=255, null=True)),
                ('commit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('commit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('repositories_link', models.ManyToManyField(to='git_api.Repositories')),
            ],
        ),
    ]
